## base image
FROM node:13.12.0-alpine

## set working directory
WORKDIR /usr/src/app

## add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

## install and cache app dependencies
COPY package.json /usr/src/app/package.json

## install git
RUN apk add --no-cache git

## install app dependencies
RUN npm install

## start app
CMD ["npm", "start"]