## base image
FROM node:13.12.0-buster-slim

## set working directory
WORKDIR /usr/src/app

## add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

## install and cache app dependencies
COPY package.json /usr/src/app/package.json

# install app dependencies
RUN npm install --silent

## start app
CMD ["npm", "start"]