apiVersion: v1
kind: Service
metadata:
  name: go-server-svc
  labels:
    app: go-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: go-server
  type: NodePort

