apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  type: LoadBalancer
  ports:
    - name: server
      protocol: TCP
      port: 3100
      targetPort: 3100
  externalIPs:
    - localhost
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
